name: UnityBuildTest-Windows-Custom-Script

on:
  workflow_dispatch:

permissions: write-all

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  buildForWindows:
    name: Build Windows
    runs-on: ubuntu-latest

    steps:
      # Step1 - Check Out
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Step2 - Cache Library
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step3 - Unity Build
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64

      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64
          buildMethod: 'Builder.BuildStandaloneWindows64' # (네임스페이스.)클래스.메서드명

      # Step4 - Upload Build File
      - name: Upload Build File
        uses: actions/upload-artifact@v4
        with:
          name: Build-Windows
          path: build/StandaloneWindows64